services:
  easemind-satellite-v1:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
    volumes:
      # - easemind_test_server_v1:/juno/.juno
      - ./juno.dev.config.mjs:/juno/juno.dev.config.mjs
      - ./target/deploy:/juno/target/deploy/
# volumes:
# easemind_test_server_v1:
